### PR TITLE
Update subssmion template:only for new layout which doesn't include cont...

### PR DESCRIPTION
**Pull request by swebshet**
...rolled Vocabulary

cg.subject.cip,cg.subject.icarda,cg.subject.drylands etc

### CODE REVIEW

**Comment by alanorth** [comment]
This is related to issue #34.  @swebsheet can you explain more what this code does?  It seems to add/remove thousands of lines, add new subjects, add new grammar, etc.

The code should do only one thing, ie: "Add new controlled vocabulary for CIP, ICARDA, and Drylands".  And if it is adding new vocabulary, it shouldn't be fixing grammar mistakes in other fields, adding new value pairs, changing help text, changing repeatables in other fields, etc.  If it changes ALL these things it makes it very hard to test, very hard to undo changes, very hard to isolate which change caused an issue, etc.

**Comment by swebshet** [comment]
I just tested it in my local machine.It works perfectly.changing repeatable>false</repeatable>to avoid long listing of list.

**Comment by alanorth** [comment]
I want the change to include one logical set of functionality.  What is this change supposed to do?  Explain it to me. :)

**Comment by swebshet** [comment]
Adding subject list  for ICARDA,CIP,drylands and also changing the layout of submssion form(Making it comapct)

**Comment by alanorth** [comment]
Ok, so those are at least two separate, logical "changes":
- Add subject lists for ICARDA, CIP, and Drylands
- Change layout of submission template to be more compact

The first one could actually be split into separate "changes" as well, ie:
- Add ICARDA subject terms
- Add CIP subject terms
- Add Drylands subject terms

When they are concisely stated like this it makes it much more easy to understand.  If you make one change that changes 10 things, it's very difficult to understand.

**Pull request closed without merging**
