### PR TITLE
additional logging to track down the missing downloads issue

### PR DESCRIPTION
**Pull request by rradillen**

### CODE REVIEW

**Comment by alanorth** [comment]
I'll merge this, but a few questions:
- Did you already apply this locally when restarting CGSpace tonight?
- After testing, do we have to revert this? (I don't know how much extra logging this does, I don't want to cause disk space issues)
- Shall I also merge it in `4_x-dev`?

**Comment by rradillen** [comment]
In normal operations it should not be triggered so disk space will not be an issue. I will have to rebuild the server for the change to take effect. It may be beneficial to first put it on dev before propagating to production.

**Comment by alanorth** [comment]
Ok, so when do you want to test this? I thought you did something regarding logging on CGSpace when you restarted it last night.

I agree we should start on development.

**Comment by alanorth** [comment]
Merged into `4_x-dev` and therefore `4_x-prod`. The problem ended up being caused by [DS-2355](https://jira.duraspace.org/browse/DS-2355), and a fix is being deployed.

**Pull request closed without merging**
